"""initial schema

Revision ID: 3401b35703e5
Revises: 
Create Date: 2026-05-18 19:36:47.811381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3401b35703e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('characteristics', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smeta_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smeta_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smeta_access_smeta_id'), 'smeta_access', ['smeta_id'], unique=False)
    op.create_index(op.f('ix_smeta_access_user_id'), 'smeta_access', ['user_id'], unique=False)
    op.create_table('smeta_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smeta_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smeta_revisions_smeta_id'), 'smeta_revisions', ['smeta_id'], unique=False)
    op.create_table('smetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_details', sa.String(), nullable=True),
    sa.Column('contractor_name', sa.String(), nullable=True),
    sa.Column('contractor_details', sa.String(), nullable=True),
    sa.Column('approver_name', sa.String(), nullable=True),
    sa.Column('approver_details', sa.String(), nullable=True),
    sa.Column('tax_mode', sa.String(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('section_adjustments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smetas_owner_id'), 'smetas', ['owner_id'], unique=False)
    op.create_index(op.f('ix_smetas_parent_id'), 'smetas', ['parent_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('smeta_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smeta_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('characteristics', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('base_unit_price', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['smeta_id'], ['smetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smeta_items_smeta_id'), 'smeta_items', ['smeta_id'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('characteristics', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['smetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_parent_id'), 'works', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_parent_id'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_smeta_items_smeta_id'), table_name='smeta_items')
    op.drop_table('smeta_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_smetas_parent_id'), table_name='smetas')
    op.drop_index(op.f('ix_smetas_owner_id'), table_name='smetas')
    op.drop_table('smetas')
    op.drop_index(op.f('ix_smeta_revisions_smeta_id'), table_name='smeta_revisions')
    op.drop_table('smeta_revisions')
    op.drop_index(op.f('ix_smeta_access_user_id'), table_name='smeta_access')
    op.drop_index(op.f('ix_smeta_access_smeta_id'), table_name='smeta_access')
    op.drop_table('smeta_access')
    op.drop_table('materials')
    # ### end Alembic commands ###
